bar = 
foo = ${bar}

all:
ifdef foo
	echo "foo is defined"
else
	echo "foo is undefined"
endif
ifdef bar
	echo "bar is defined"
else
	echo "bar is undefined"
endif
ifdef test
	echo "test is defined"
else
	echo "test is undefined"
endif


